### ISSUE TITLE
Cannot read configuration file

### ISSUE THREAD

**Issue by svj1090** [kevinsea/dsc-generator#1]
Hi,

I built the code and copied the exe to a windows 2008 box and tried to create dsc configuration for IIS and it throws below error. i tried going through the code and find the issue but so far no success. Could you please look in to it.

Filename: redirection.config
Error: Cannot read configuration file

Thanks
SJ
![dsc-generator-error](https://cloud.githubusercontent.com/assets/12264223/13656605/29fed1b6-e61d-11e5-948a-83d37dd2ba00.png)

**Comment by kevinsea** [comment]
Hi,

I found this post
http://stackoverflow.com/questions/13727454/what-is-this-vague-error-with-redirection-config-while-building-a-web-deploy-p

Does the logged in account have access to %SystemRoot%\System32\inetsrv\config
?

Best,

Kevin

**Comment by svj1090** [comment]
Hey Kevin,

I did some debugging using processmon and noticed that it was looking for
applicationhost/redirection.config files from
C:\user\currentuser\documents\IISExpress\Config when I try to generate IIS
configuration but when I click to generate features configuration it reads
the config from right path.

Thanks
Sanjay

**Comment by kevinsea** [comment]
Sorry for the slow response.  I believe this is related to issue #2 where the dll version you had locally was off.  Can you see if its still an issue with the latest version?

**Comment by kevinsea** [comment]
Closing, but please reopen if the it was not solved by #2.
