### ISSUE TITLE
Getting it to build in Visual Studio

### ISSUE THREAD

**Issue by technoe** [kevinsea/dsc-generator#10]
I'm pretty new to coding and building solutions but I can't seem to get the solution to build into anything.  I just get a bunch of errors. Are there some instructions somewhere for getting this to build?

**Comment by kevinsea** [comment]
You are using VS 2015?  What kind of errors?

**Comment by technoe** [comment]
Originally I was getting errors regarding an extra '$' in several files. Now I'm getting errors regarding Microsoft.Web.Administration. 
 IIS\WebAuthenticationInformation.cs (6): The type or namespace name 'Web' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

**Comment by kevinsea** [comment]
If its complaining about the $, you are running < VS 2015.  Its a new way to do string.format added in 2015.

**Comment by technoe** [comment]
Right. I fixed that and I think I found the solution to my other issue as well. I just needed to install some other features from the 2015 install. I'll report back tomorrow.

**Comment by technoe** [comment]
Ok, I got it to build. I had to disable OneClick in the proj properties.
