### ISSUE TITLE
System Type Initialization Exception 

### ISSUE THREAD

**Issue by hopenbr** [kevinsea/dsc-generator#2]
Hello 

I have compiled code and am trying to run the DCS Generator on Win 2012 R2 IIS 8.5 with default settings.  
PowerShell Version 5 is running.  

It runs and immediately pop up error box System.TypeInitializationException 

I was able to get that it hits at IISObjectFactory.cs Line 16. 

The generator run fine when select the bottom box 'Generate IIS Windows Features'  

It only errors when I select 'Generate IIS Sites and Pools' with any of the sub button checked. 

Thanks a Million, 

Brian

**Comment by hopenbr** [comment]
I fixed the error Microsoft.Web.Administration.dll was grabbing my local IIS Express version 7.9.0.0, so I went to nuget and got the 7.0.0.0 version.  Now it is working great.  Might want to think about move your references to be nuget based.  

Brian

**Comment by kevinsea** [comment]
Yes, a nuget reference sounds better, I'll do that.

**Comment by kevinsea** [comment]
Thanks for digging into the issue.  I have changed the reference to use nuget.
