### ISSUE TITLE
Sequence contains no matching element (InvalidOperationException)

### ISSUE THREAD

**Issue by mkeller25** [kevinsea/dsc-generator#8]
![image](https://cloud.githubusercontent.com/assets/21065741/17740747/b13cb062-6467-11e6-843f-a2d97ad75ae3.png)

**Comment by kevinsea** [comment]
Hmm, I'll do some work on that error window to make the message helpful.

Can you tell me a bit about the computer?  E.g. Windows server 2012 R2, IIS
7.5.

**Comment by mkeller25** [comment]
Server 2012. I'll get the exact version of IIS but it's definitely 7.
On Aug 19, 2016 8:29 AM, Kevin Callahan notifications@github.com wrote:Hmm, I'll do some work on that error window to make the message helpful.

Can you tell me a bit about the computer?  E.g. Windows server 2012 R2, IIS
7.5.

**Comment by kevinsea** [comment]
I just added a better error window that will also include the stack trace.  Can you use that and send along the information you get?

**Comment by mkeller25** [comment]
Will do on Monday. Thanks

**Comment by kevinsea** [comment]
I think I just fixed the underlying issue as well.

**Comment by mkeller25** [comment]
Its now working on the server where it was previously failing.

**Comment by kevinsea** [comment]
Great
