### ISSUE TITLE
Where are "OrphanedApps" & "OrphanedApps_Pool" coming from?

### ISSUE THREAD

**Issue by mkeller25** [kevinsea/dsc-generator#9]
See image below. Looking at the web server, all I can figure is that these are "old" sites that are no longer in use. In fact, they aren't showing up in IIS or in the website directories at all so.... how are these being created or where are they coming from? 

In the meantime I'm going to go through and manually pull all these lines out of the generated DSC code.

![image](https://cloud.githubusercontent.com/assets/21065741/17979725/1a735258-6aca-11e6-8f1a-811667a32dbb.png)

**Comment by kevinsea** [comment]
I've never seen that and I've run this on a bunch of hacked up servers...that is weird.

There is a config file that defines sites, app pools, etc.  I would expect you'd find them in there. From your system folder its "\inetsrv\config\applicationHost.config".

As far as a code fix It seems reasonable to either 1) handle the lack of an app pool more gracefully or 2) skip sites that don't have a valid app pool.
